### ISSUE TITLE
ln(e^(i*π))  doesn't calculate

### ISSUE THREAD

**Issue by mbkma** [mate-desktop/mate-calc#100]
#### Expected result
πi
#### Actual behaviour
It calculates forever.
It seems to be an infinite loop. Probably somewhere in mp.c where ln() is defined.
#### MATE general version
1.20.1
#### Package version
1.22.0
#### Linux Distribution
Ubuntu Mate 18.04

**Comment by sc0w** [comment]
confirmed in mate-calc 1.20.3

![2019-04-24_18-00](https://user-images.githubusercontent.com/7734191/56674845-0e849c00-66bb-11e9-95e8-b406d7baf730.png)

**Comment by willysr** [comment]
Confirmed in 1.22.0 as well

**Comment by sc0w** [comment]
It **doesn't work** in **gnome-calculator 3.11.90**

It **works** in **gnome-calculator 3.12.0**

**Comment by sc0w** [comment]
seems it was fixed for gnome-calculator with https://gitlab.gnome.org/GNOME/gnome-calculator/commit/6eb0f2b5e6df456a97a796b35d811376a69679e0

**Comment by sc0w** [comment]
It seems to be related the function `mp_ln_real` in `/src/mp.c`

**Comment by rbuj** [comment]
```shell
(gdb) backtrace                                                                                                                                          
#0  0x000000000041f0c4 in mp_set_from_float (rx=<optimized out>, z=z@entry=0x7fffcd7e8060) at mp-convert.c:54
#1  0x000000000041df60 in mp_ln_real (x=x@entry=0x7fffcd7f1d20, z=z@entry=0x7fffcd7f5bc0) at mp.c:1256
#2  0x000000000041e31e in mp_ln (x=x@entry=0x7fffd0013bf0, z=z@entry=0x7fffd0011c90) at mp.c:1297
#3  0x00000000004206d6 in get_function (state=0x7fffd000fcd0, name=0x7fffd00015c0 "ln", x=0x7fffd0013bf0, z=0x7fffd0011c90) at mp-equation.c:173
#4  0x0000000000427962 in pf_apply_func (self=0x7fffd0004e10) at parserfunc.c:306
#5  0x0000000000429b1b in p_parse (state=state@entry=0x7fffd000fcd0) at parser.c:276
#6  0x0000000000421139 in mp_equation_parse (expression=expression@entry=0xd9ccc0 "ln(e^(i×π))", options=options@entry=0x7fffcd7f7be0, result=result@entry=0x7fffcd7f7c30, error_token=error_token@entry=0x7fffcd7f7bd8) at mp-equation.c:266
#7  0x0000000000415ec1 in parse (error_token=0x7fffcd7f7bd8, z=0x7fffcd7f7c30, text=<optimized out>, equation=0x4faa90) at math-equation.c:1184
#8  0x0000000000415ec1 in math_equation_solve_real (data=<optimized out>) at math-equation.c:1219
#9  0x00007ffff716f752 in  () at /lib64/libglib-2.0.so.0
#10 0x00007ffff6f975a2 in start_thread () at /lib64/libpthread.so.0
#11 0x00007ffff6ec4023 in clone () at /lib64/libc.so.6
```

**Comment by rbuj** [comment]
```
e^(i*π) = cos(π) + sin(π)i = -1 + 0i = -1
ln(-1) = ERROR
```
